import Head from 'next/head'

import { IBanner, ICategory,  INewRealease, ZingMp3Response } from '../src/types/ZingMP3Response.type'
import { getHome } from '@/src/service/zingmp3.service'
import Banner from '@/src/components/Banner'
import NewRelease from '@/src/components/NewRealase'
import Category from '@/src/components/Category'



export default function Home({data}:ZingMp3Response ) {
  // getdata banner from data
  const banner:IBanner = data.data.items?.filter((item: any) => item.sectionType==='banner')[0]
  // getdata new release from data
  const newRelease:INewRealease = data.data.items?.filter((item: any) => item.sectionType==='new-release')[0]
  // getdata category chill from data
  const chillCategory:ICategory = data.data.items?.filter((item: any) => item.title==='Chill')[0]
  // getdata category happy weekend from data
  const happyWeekend:ICategory = data.data.items?.filter((item: any) => item.title==='Happy weekend')[0]
  // getdata category Nghệ sĩ thịnh hành from data
  const artists:ICategory = data.data.items?.filter((item: any) => item.title==='Nghệ sĩ thịnh hành')[0]
  return (
      <>
        <Head>
          <title>Zing MP3</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Banner banner={banner}/>
        <NewRelease newRelease={newRelease}/>
        <Category category={chillCategory}/>
        {happyWeekend && <Category category={happyWeekend}/>} 
        <Category category={artists}/>
      </>
  )
}

export async function getStaticProps() {
  const data: ZingMp3Response = await getHome()
  return {
    props: {
      data,
    },
    revalidate: 60,
  }
}